sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t shengcer/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shengcer/docker-react npm run test -- --coverage